version: '3'

volumes:
  prometheus-data:
  grafana-data:
  loki-data:

services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - prometheus-data:/prometheus
    restart: unless-stopped
    environment:
      - BACTOCLOUD_USERNAME=${BACTOCLOUD_USERNAME}
      - BACTOCLOUD_PASSWORD=${BACTOCLOUD_PASSWORD}
      - BACTOCLOUD_HOST=${BACTOCLOUD_HOST}
      - BACTOCLOUD_PORT=${BACTOCLOUD_PORT}
    entrypoint:
      - /bin/sh
      - -c
      - |
        mkdir -p /etc/prometheus
        cat > /etc/prometheus/prometheus.yml << EOL
        global:
          scrape_interval: 15s
          evaluation_interval: 15s

        scrape_configs:
          - job_name: "prometheus"
            static_configs:
              - targets: ["localhost:9090"]

          - job_name: "node_exporter"
            static_configs:
              - targets: ["node_exporter:9100"]

          - job_name: "cadvisor"
            static_configs:
              - targets: ["cadvisor:8080"]
              
          - job_name: "bactocloud"
            basic_auth:
              username: "${BACTOCLOUD_USERNAME}"
              password: "${BACTOCLOUD_PASSWORD}"
            static_configs:
              - targets: ["${BACTOCLOUD_HOST}:${BACTOCLOUD_PORT}"]
            metrics_path: "/metrics"
        EOL
        
        /bin/prometheus --config.file=/etc/prometheus/prometheus.yml --storage.tsdb.path=/prometheus --web.listen-address=0.0.0.0:9090

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3001:3000"
    volumes:
      - grafana-data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_INSTALL_PLUGINS=grafana-loki-datasource
    restart: unless-stopped
    entrypoint:
      - /bin/bash
      - -c
      - |
        mkdir -p /etc/grafana/provisioning/datasources
        cat > /etc/grafana/provisioning/datasources/datasource.yml << 'EOL'
        apiVersion: 1

        datasources:
          - name: Prometheus
            type: prometheus
            access: proxy
            url: http://prometheus:9090
            isDefault: true
            editable: true
          
          - name: Loki
            type: loki
            access: proxy
            url: http://loki:3100
            editable: true
        EOL
        
        mkdir -p /var/lib/grafana/dashboards
        cat > /var/lib/grafana/dashboards/default.json << 'EOL'
        {
          "annotations": {
            "list": []
          },
          "editable": true,
          "gnetId": null,
          "graphTooltip": 0,
          "links": [],
          "panels": [
            {
              "datasource": "Prometheus",
              "description": "System load average",
              "fieldConfig": {
                "defaults": {
                  "color": {
                    "mode": "palette-classic"
                  },
                  "custom": {
                    "axisLabel": "",
                    "axisPlacement": "auto",
                    "barAlignment": 0,
                    "drawStyle": "line",
                    "fillOpacity": 10,
                    "gradientMode": "none",
                    "hideFrom": {
                      "legend": false,
                      "tooltip": false,
                      "viz": false
                    },
                    "lineInterpolation": "linear",
                    "lineWidth": 1,
                    "pointSize": 5,
                    "scaleDistribution": {
                      "type": "linear"
                    },
                    "showPoints": "never",
                    "spanNulls": false
                  },
                  "mappings": [],
                  "thresholds": {
                    "mode": "absolute",
                    "steps": [
                      {
                        "color": "green",
                        "value": null
                      },
                      {
                        "color": "red",
                        "value": 80
                      }
                    ]
                  },
                  "unit": "none"
                },
                "overrides": []
              },
              "gridPos": {
                "h": 8,
                "w": 12,
                "x": 0,
                "y": 0
              },
              "id": 1,
              "options": {
                "legend": {
                  "calcs": [],
                  "displayMode": "list",
                  "placement": "bottom"
                },
                "tooltip": {
                  "mode": "single"
                }
              },
              "pluginVersion": "8.0.0",
              "targets": [
                {
                  "exemplar": true,
                  "expr": "node_load1",
                  "interval": "",
                  "legendFormat": "1m",
                  "refId": "A"
                },
                {
                  "exemplar": true,
                  "expr": "node_load5",
                  "interval": "",
                  "legendFormat": "5m",
                  "refId": "B"
                },
                {
                  "exemplar": true,
                  "expr": "node_load15",
                  "interval": "",
                  "legendFormat": "15m",
                  "refId": "C"
                }
              ],
              "title": "System Load Average",
              "type": "timeseries"
            }
          ],
          "refresh": "5s",
          "schemaVersion": 30,
          "style": "dark",
          "tags": [],
          "templating": {
            "list": []
          },
          "time": {
            "from": "now-1h",
            "to": "now"
          },
          "timepicker": {},
          "timezone": "",
          "title": "Default Dashboard",
          "version": 1
        }
        EOL
        
        cat > /etc/grafana/grafana.ini << 'EOL'
        [dashboards]
        default_home_dashboard_path = /var/lib/grafana/dashboards/default.json
        EOL
        
        /run.sh

  loki:
    image: grafana/loki:latest
    container_name: loki
    ports:
      - "3100:3100"
    volumes:
      - loki-data:/loki
    command: -config.file=/etc/loki/local-config.yaml
    restart: unless-stopped
    entrypoint:
      - /bin/sh
      - -c
      - |
        mkdir -p /etc/loki
        cat > /etc/loki/local-config.yaml << 'EOL'
        auth_enabled: false

        server:
          http_listen_port: 3100

        ingester:
          lifecycler:
            address: 127.0.0.1
            ring:
              kvstore:
                store: inmemory
              replication_factor: 1
            final_sleep: 0s
          chunk_idle_period: 5m
          chunk_retain_period: 30s

        schema_config:
          configs:
            - from: 2020-05-15
              store: boltdb-shipper
              object_store: filesystem
              schema: v11
              index:
                prefix: index_
                period: 24h

        storage_config:
          boltdb_shipper:
            active_index_directory: /loki/boltdb-shipper-active
            cache_location: /loki/boltdb-shipper-cache
            cache_ttl: 24h
            shared_store: filesystem
          filesystem:
            directory: /loki/chunks

        limits_config:
          enforce_metric_name: false
          reject_old_samples: true
          reject_old_samples_max_age: 168h
          ingestion_rate_mb: 30
          ingestion_burst_size_mb: 60

        chunk_store_config:
          max_look_back_period: 168h

        table_manager:
          retention_deletes_enabled: true
          retention_period: 72h
        EOL
        
        /usr/bin/loki -config.file=/etc/loki/local-config.yaml

  promtail:
    image: grafana/promtail:latest
    container_name: promtail
    ports:
      - "9080:9080"  # Expose promtail push API port
    volumes:
      - /var/log:/var/log
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
    command: -config.file=/etc/promtail/config.yml
    depends_on:
      - loki
    restart: unless-stopped
    entrypoint:
      - /bin/sh
      - -c
      - |
        mkdir -p /etc/promtail
        cat > /etc/promtail/config.yml << 'EOL'
        server:
          http_listen_port: 9080
          grpc_listen_port: 0

        positions:
          filename: /tmp/positions.yaml

        clients:
          - url: http://loki:3100/loki/api/v1/push

        scrape_configs:
          # For logs from local Docker containers
          - job_name: docker
            static_configs:
              - targets:
                  - localhost
                labels:
                  job: docker
                  __path__: /var/lib/docker/containers/*/*log

          # For logs from local system
          - job_name: system
            static_configs:
              - targets:
                  - localhost
                labels:
                  job: syslog
                  __path__: /var/log/syslog
                  
          # HTTP Push API for external clients
          - job_name: push-api
            loki_push_api:
              server:
                http_listen_port: 9080
                grpc_listen_port: 0
              labels:
                job: push-api
        EOL
        
        /usr/bin/promtail -config.file=/etc/promtail/config.yml

  node_exporter:
    image: quay.io/prometheus/node-exporter:latest
    container_name: node_exporter
    command:
      - '--path.rootfs=/host'
    pid: host
    restart: unless-stopped
    volumes:
      - '/:/host:ro,rslave'

  cadvisor:
    image: google/cadvisor:latest
    container_name: cadvisor
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
    devices:
      - /dev/kmsg
    restart: unless-stopped